// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTwoOG93ywUe_lPdHzqCVhhE2ukeZAXO8',
    appId: '1:789996709547:web:dad585427d57b4f117f9ee',
    messagingSenderId: '789996709547',
    projectId: 'bakryexcel',
    authDomain: 'bakryexcel.firebaseapp.com',
    storageBucket: 'bakryexcel.appspot.com',
    measurementId: 'G-3TX2R9QWTV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrlgmgGUNXWMvWRawl-7E3yU1RPt9FSPo',
    appId: '1:789996709547:android:25c38bd3f75a2ce517f9ee',
    messagingSenderId: '789996709547',
    projectId: 'bakryexcel',
    storageBucket: 'bakryexcel.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDQQysR554rcHc2mgzpgycKcBvl0dNoFw',
    appId: '1:789996709547:ios:f2c3e4a88ac7da6617f9ee',
    messagingSenderId: '789996709547',
    projectId: 'bakryexcel',
    storageBucket: 'bakryexcel.appspot.com',
    iosBundleId: 'com.example.bakryapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDQQysR554rcHc2mgzpgycKcBvl0dNoFw',
    appId: '1:789996709547:ios:f2c3e4a88ac7da6617f9ee',
    messagingSenderId: '789996709547',
    projectId: 'bakryexcel',
    storageBucket: 'bakryexcel.appspot.com',
    iosBundleId: 'com.example.bakryapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTwoOG93ywUe_lPdHzqCVhhE2ukeZAXO8',
    appId: '1:789996709547:web:c4ef9b038ba54c4c17f9ee',
    messagingSenderId: '789996709547',
    projectId: 'bakryexcel',
    authDomain: 'bakryexcel.firebaseapp.com',
    storageBucket: 'bakryexcel.appspot.com',
    measurementId: 'G-5TE7ZH3MH6',
  );

}